local({
  pkg_name <- "rk.universe"
  dir.create(pkg_name, showWarnings = FALSE)
  dir.create(file.path(pkg_name, "R"), showWarnings = FALSE)
  dir.create(file.path(pkg_name, "man"), showWarnings = FALSE) # NUEVO: Carpeta de ayuda

  # La lista completa de tus 62 paquetes
  mis_paquetes <- c(
    "rk.haven", "rk.efa", "rk.quarto", "rk.subset.tidy", "rk.flextable",
    "rk.survey.design", "rk.questionr", "rk.exporter", "rk.gtsummary",
    "rk.gganimate", "rk.fastdummies", "rk.grateful", "rk.case.if", "rk.rmd",
    "rk.storytelling.survey", "rk.names.labels", "rk.text.mining", "rk.ipumsr",
    "rk.word.cloud", "rk.interactive.bi", "rk.effect.sizes", "rk.ggsurvey",
    "rk.tidycensus", "rk.weibull", "rk.ddi.import", "rk.shiny.plugins",
    "rk.googlesheets4", "rk.network.graphs", "rk.forcats", "rk.dates",
    "rk.ctables", "rk.codebook", "rk.class.lists", "rk.bayesian",
    "rk.correspondence", "rk.map.globalities", "rk.cartographr", "rk.aiken.v",
    "rk.stringr", "rk.dplyr", "rk.janitor", "rk.lubridate", "rk.apyramid",
    "rk.map.localities", "rk.rnaturalearth", "rk.survey.wrangling",
    "rk.storytelling.data", "rk.data.wrangling", "rk.pivot.reshape",
    "rk.cSplit", "rk.mult.resp", "rk.svyplot", "rk.transpose.df", "rk.psych",
    "rk.six.sigma", "rk.lookup", "rk.doe", "rk.lavaan", "rk.qcc",
    "rk.survival", "rk.tidyr", "rk.gsub.sub"
  )

  # =========================================================================
  # 1. CREAR EL ARCHIVO DESCRIPTION
  # =========================================================================
  desc_content <- c(
    "Package: rk.universe",
    "Type: Package",
    "Title: The Ultimate RKWard Plugin Ecosystem",
    "Version: 0.1.2",
    "Authors@R: person(\"Alfonso\", \"Cano\", email = \"alfonso.cano@correo.buap.mx\", role = c(\"aut\", \"cre\"))",
    "Description: A meta-package that automatically installs, loads, and synchronizes a massive suite of 62+ RKWard GUI plugins for data manipulation, statistical analysis, and academic publishing.",
    "License: GPL (>= 3)",
    "URL: https://github.com/AlfCano/rk.universe",
    "Encoding: UTF-8",
    "Imports:",
    "    cli,",
    paste0("    ", paste(mis_paquetes, collapse = ",\n    ")),
    "RoxygenNote: 7.3.1"
  )
  writeLines(desc_content, file.path(pkg_name, "DESCRIPTION"))

  # =========================================================================
  # 2. CREAR EL ARCHIVO NAMESPACE (NUEVO - Evita Warnings)
  # =========================================================================
  ns_content <- c(
    "# Generated by roxygen2: do not edit by hand",
    "export(rk_universe_packages)"
  )
  writeLines(ns_content, file.path(pkg_name, "NAMESPACE"))

  # =========================================================================
  # 3. CREAR DOCUMENTACIÓN .Rd (NUEVO - Evita Warnings de funciones no doc.)
  # =========================================================================
  rd_content <- c(
    "\\name{rk_universe_packages}",
    "\\alias{rk_universe_packages}",
    "\\title{List all packages in rk.universe}",
    "\\usage{rk_universe_packages()}",
    "\\description{Returns a character vector of all RKWard plugins included in the ecosystem.}",
    "\\value{A character vector.}"
  )
  writeLines(rd_content, file.path(pkg_name, "man", "rk_universe_packages.Rd"))

  # =========================================================================
  # 4. CREAR EL ARCHIVO MÁGICO (R/zzz.R)
  # =========================================================================
  zzz_content <- c(
    "#' List all packages in rk.universe",
    "#' @export",
    "rk_universe_packages <- function() {",
    paste0("  c(\"", paste(mis_paquetes, collapse = "\", \""), "\")"),
    "}",
    "",
    ".onAttach <- function(libname, pkgname) {",
    "  pkgs <- rk_universe_packages()",
    "  ",
    "  # 1. Attach packages silently (Estilo tidyverse, evita Warnings)",
    "  loaded_count <- 0",
    "  suppressPackageStartupMessages({",
    "    for (pkg in pkgs) {",
    "      if (requireNamespace(pkg, quietly = TRUE)) {",
    "        if (!paste0(\"package:\", pkg) %in% search()) {",
    "          library(pkg, character.only = TRUE, warn.conflicts = FALSE)",
    "        }",
    "        loaded_count <- loaded_count + 1",
    "      }",
    "    }",
    "  })",
    "  ",
    "  # 2. Print beautiful CLI header",
    "  cli::cli_rule(",
    "    left = cli::style_bold(\"rk.universe ecosystem 0.1.2\"),",
    "    right = \"RKWard GUI Suite\"",
    "  )",
    "  ",
    "  if (loaded_count == length(pkgs)) {",
    "    cli::cli_alert_success(\"Successfully loaded all {loaded_count} packages.\")",
    "  } else {",
    "    cli::cli_alert_warning(\"Loaded {loaded_count}/{length(pkgs)} packages. Some may not be installed.\")",
    "  }",
    "  ",
    "  # 3. RKWard Pluginmap Auto-Registration",
    "  is_rkward <- (\"package:rkward\" %in% search()) || (\"rkward\" %in% loadedNamespaces())",
    "  ",
    "  if (is_rkward) {",
    "    registered_count <- 0",
    "    for (pkg in pkgs) {",
    "      map_paths <- list.files(system.file(\"rkward\", package = pkg), pattern = \"\\\\.pluginmap$\", full.names = TRUE)",
    "      ",
    "      for (m in map_paths) {",
    "        eval(parse(text = sprintf(\"rkward::rk.register.pluginmap('%s', deinstall = FALSE)\", m)))",
    "        registered_count <- registered_count + 1",
    "      }",
    "    }",
    "    ",
    "    if (registered_count > 0) {",
    "      cli::cli_alert_success(\"RKWard environment detected: {registered_count} GUI menus activated.\")",
    "    }",
    "  } else {",
    "    cli::cli_alert_info(\"Running outside RKWard. GUI menus will be available when opened in RKWard.\")",
    "  }",
    "  cli::cli_rule()",
    "}"
  )
  writeLines(zzz_content, file.path(pkg_name, "R", "zzz.R"))

  cat("\nMeta-package 'rk.universe' (v0.1.2) generated successfully!\n")
})
